---
title: Synopsis for Umeå
---
With the first paper of my thesis, I contribute to the bioeconomy transition debate in Sweden.
Previous research has mapped out the discourse, its central actors and their key aims, finding three competing visions for a bioeconomy.
The biotechnology vision is most dominant outside the EU, focusing on the scientific exploitation of biological material for new technologies.
The bioresource vision, heavily promoted by the Swedish forstry industry, focuses on processess and upgrading of product value chains.
A counter vision centering on ecological aspects draws these first visions into question, proposing instead a reoriented economy embedded within the ecological limits.

By classifiying significant Swedish innovations from 1970 onwards identified by the SWINNO project, accroding to their corresponding visions, my paper moves beyond intent and analyses the concrete direction taken by the transition.
At Umeå I look forward to presenting preliminary results and the method used for classifying the innovations.
Input on the validity of the approach as well as discussions about strategies to mitigate data biases favoring the biotechnology and bioresource vision are much appreciated.
I will circulate the data together with a detailed method description beforehand.

For more information about my PhD project and how this paper fits in, please visit [pjkreutzer.github.io/research](pjkreutzer.github.io/research), where you will also find a research plan.
