```{r}
library(dplyr)
library(ggplot2)
library(scales)
library(patchwork)
library(showtext)
library(paletteer)
library(rio)
library(here)
library(hrbrthemes)
library(stringr)

showtext_auto()
font_add_google("IBM Plex Sans", "IBMPlexSans")

theme_custom <- function() {
    ret <- hrbrthemes::theme_ipsum_ps(grid = "Y")
    ret <- ret + theme(axis.line.x = element_line(color = "black", linewidth = 0.5))
    ret
}
```


```{r}
bioeconomy_share <- import(here("data/modified/swinno_bioeconomy_share.csv"))
```


```{r}

plot_bioeconomy_stats <- function(df, y, yaxis_title) {
    ggplot(df, aes(x = year, y = .data[[y]])) +
        geom_area(color="black", fill = "gray40", alpha = 0.5, linewidth=1) +
        xlab("Year") +
        ylab(stringr::str_wrap(yaxis_title, width = 20)) +
        theme_custom()
}
```


```{r}
#| label: fig-n-bioeconomy
bioeconomy_plot <- plot_bioeconomy_stats(bioeconomy_share, "ma5_n_bioeconomy", "Forest Bioeconomy")
```


```{r}
#| label: fig-n-innovation

innovation_plot <- plot_bioeconomy_stats(bioeconomy_share, "ma5_n_innovation", "Total SWINNO")
```


```{r}
#| label: fig-share
share_plot <- plot_bioeconomy_stats(bioeconomy_share, "ma5_share_bioeconomy", "Forest Bioeconomy Share") + scale_y_continuous(label = percent)
share_plot
```


```{r}
#| label: fig-trends

innovation_trends_plot  <- (innovation_plot + bioeconomy_plot) / share_plot + plot_annotation(tag_levels = "a") & theme(plot.margin = margin(t = 0, 
                             r = 1,  # Right margin
                             b = 0,  # Bottom margin
                             l = 0))

innovation_trends_plot
ggsave(here("results/figures/innovation_trends.pdf"), width=7, height=5)
```

## Bioeconomy Visions Plot


```{r}
visions <- import(here("data/modified/count_certain_visions.csv"))

vision_summary <- visions |>
    group_by(bioeconomy_vision) |>
    summarize(total_count = sum(count))

visions <- merge(visions, vision_summary, by = "bioeconomy_vision")

```


```{r}
batlow_discrete <- , n = 5)
```


```{r}
paletteer::paletteer_c("scico::batlowW", n = 7)
```
```{r}
#| label: fig-vision-count
vision_count_plot <- ggplot(visions, aes(x = year, y = count, color = bioeconomy_vision, fill = bioeconomy_vision)) +
    geom_col(alpha = 0.9, linewidth = 0.75) +
    facet_wrap(~bioeconomy_vision) +
    scale_color_manual(values = batlow_discrete) +
    scale_fill_manual(values = batlow_discrete) +
    theme_custom() +
    theme(legend.position = "none") +
    scale_y_continuous(breaks = seq(0, max(visions$count), by = 2), expand = c(0, 0)) +
    xlab("Year") +
    ylab("Innovation Count") +
    geom_text(
        data = vision_summary, aes(label = paste("Total:", total_count), x = Inf, y = Inf),
        position = position_nudge(y = 0), hjust = 1, vjust = 1.3, size = 3.5
    )

ggsave(here("results/figures/vision_count.png"), vision_count_plot)
```

```{r}
#| label: fig-visions-stacked-area

# Reorder the levels of bioeconomy_vision based on the sum of counts
visions$bioeconomy_vision <- factor(visions$bioeconomy_vision,
    levels = vision_summary$bioeconomy_vision[order(vision_summary$total_count, decreasing = TRUE)]
)

p <- ggplot(visions, aes(x = year, y = count, fill = bioeconomy_vision, color = bioeconomy_vision)) +
    geom_area(color = "black", alpha = 0.8) +
    scale_fill_manual(values = batlow_discrete, name = "Bioeconomy Vision") + # Set legend title
    scale_color_manual(values = batlow_discrete, guide = "none") + # Hide color legend
    theme_custom() +
    theme(legend.position = c(0.9, 0.9)) +
    scale_y_continuous(expand = c(0, 0)) +
    labs(color = NULL)

p

```
